[build-system]
requires = ['flit_core>=3.4,<4']
build-backend = 'flit_core.buildapi'

[project]
name = 'aiida-shell'
dynamic = ['version']
description = 'AiiDA plugin that makes running shell commands easy.'
authors = [
    {name = 'Sebastiaan P. Huber', email = 'mail@sphuber.net'}
]
readme = 'README.md'
license = {file = 'LICENSE.txt'}
classifiers = [
        'Development Status :: 3 - Alpha',
        'Framework :: AiiDA',
        'License :: OSI Approved :: MIT License',
        'Operating System :: POSIX :: Linux',
        'Operating System :: MacOS :: MacOS X',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Topic :: Scientific/Engineering'
]
keywords = ['aiida', 'workflows']
requires-python = '>=3.8'
dependencies = [
    'aiida-core~=2.0.0b1',
]

[project.urls]
Source = 'https://github.com/sphuber/aiida-shell'

[project.optional-dependencies]

[tool.flit.module]
name = 'aiida_shell'

[tool.flit.sdist]
exclude = [
    '.gitignore/',
    'tests/',
]
